---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: clo835
  region: "us-east-1"
  version: "1.26"

availabilityZones: ["us-east-1a" ,"us-east-1b" ,"us-east-1c"]
iam:
  serviceRoleARN: arn:aws:iam::132456686334:role/LabRole

cloudWatch:
  clusterLogging:
    enableTypes: ["authenticator"]
    
managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small
  ssh:
    enableSsm: true
  iam:
    instanceRoleARN: arn:aws:iam::132456686334:role/LabRole