apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: application-hpa
  namespace: final
  labels:
    app: employees
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30