apiVersion: v1
kind: Service
metadata:
  name: mysql-service
<<<<<<< HEAD
  namespace: sqldb
=======
  namespace: final
>>>>>>> 39ca512 (minor fixes to the yaml files)
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306