apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-mysql
<<<<<<< HEAD
  namespace: sqldb
=======
  namespace: final
>>>>>>> 39ca512 (minor fixes to the yaml files)
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-img
          image: 132456686334.dkr.ecr.us-east-1.amazonaws.com/mysql-img:mysql_version_1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345"
          ports:
            - containerPort: 3306