apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
<<<<<<< HEAD
  namespace: sqldb
=======
  namespace: final
>>>>>>> 39ca512 (minor fixes to the yaml files)
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  
  