apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: sqldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: aws-gp2