apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::132456686334:role/LabRole

  #Account id updated from AWS account, each time eks cluster is newly created.
