apiVersion: v1
kind: Service
metadata:
  name: frontend-service
<<<<<<< HEAD
  namespace: webapp
=======
  namespace: final
>>>>>>> 39ca512 (minor fixes to the yaml files)
  labels:
    app: employees 
    component: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 81
      nodePort: 30000
  selector:
    app: employees