apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: employees
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
        component: frontend
    spec:
      serviceAccountName: clo835
      containers:
        - name: application-container
          image: 132456686334.dkr.ecr.us-east-1.amazonaws.com/websrv-img:webserver_version_10.7
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-password
                  key:  MYSQL_ROOT_PASSWORD
            - name: DBUSER
              value: root
            - name: DBHOST
              value: "mysql-service.final.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: bucket
            - name: BGIMG
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: bgimg
            - name: GRPNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: grpname
          resources:
            requests:
              cpu: 15m
            limits:
              cpu: 50m
          ports:
            - containerPort: 81