apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: final
  labels:
    app: employees
    component: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 81
      nodePort: 30000
  selector:
    app: employees
